= C++ Ecosystem International Standard Draft Sources

These are the sources used to generate drafts of the {CPP} Ecosystem
International Standard. These sources should not be considered an ISO
publication, nor should documents generated from them unless officially adopted
by the {CPP} working group (ISO/IEC JTC1/SC22/WG21).

== Get Involved

This draft is being developed by the WG21/SG15 Tooling Study Group. To get
involved in the development you can:

* https://isocpp.org/std/meetings-and-participation[Find out how to participate in WG21 activities.]

* https://lists.isocpp.org/mailman/listinfo.cgi/sg15[Join the discussions through the WG21/SG15 reflector.]

== Getting Started

=== Asciidoctor

You'll need the latest https://asciidoctor.org/[Asciidoctor] version 2. Consult
their https://asciidoctor.org/#installation[installation] instructions for ways
to obtain it.

=== B2

The https://www.bfgroup.xyz/b2/[B2] build system is needed to manage the
translation steps from the Asciidoctor sources, to LaTex+PDF and to HTML.

=== LaTeX

You'll need a sufficiently recent and capable LaTeX distribution installed and
accessible in the default execution path. The
https://www.tug.org/texlive/[TeX Live] distribution is the most complete in that
regard and is available in the regular platforms. You can consult either/or
the instructions in the TeX Live documentation or the package manager for your
OS. You'll want to make sure you can execute the `latexmk` command. Here are
some quick instructions for some common systems:

[cols="0,1",frame=ends,grid=rows,stripes=even]
|===

| *Arch Linux*
a|
[source,shell]
----
> sudo pacman -S texlive-latexextra texlive-binextra texlive-plaingeneric texlive-fontsrecommended
----

| *Ubuntu, Debian, etc*
a|
[source,shell]
----
> sudo apt-get install latexmk texlive-latex-recommended texlive-latex-extra \
   texlive-fonts-recommended lmodern
----

| *Fedora*
a|
[source,shell]
----
> dnf install latexmk texlive texlive-isodate texlive-relsize texlive-ulem \
   texlive-fixme texlive-extract texlive-l3kernel texlive-l3packages \
   texlive-splitindex texlive-imakeidx
----

| *MacOS*
| Install https://www.tug.org/mactex/[MacTeX].

| *Windows*
| Consult https://www.tug.org/texlive/windows.html[TeXLive instructions].

|===

=== Visual Studio Code

This repo is set up to work nicely with vscode. In particular if you install
https://open-vsx.org/extension/James-Yu/latex-workshop[LaTeX Workshop]. Assuming
you have the appropriate LaTeX tools installed and accessible vscode will
automatically build a PDF you can preview in vscode and edit `tex` files
semi-live. The resulting built files and PDF are placed in the
`${workspaceFolder}/.build/vscode` directory.
